### ISSUE TITLE
json: dividere in categorie frasi.json

### ISSUE THREAD

**Issue by dag7dev** [dag7dev/MozItaReBot#11]
(es. le stringhe dei bottoni vanno sotto una categoria che si chiama buttons)

**Comment by Trafitto** [comment]
Ciao, posso risolvere questa issue?

**Comment by dag7dev** [comment]
> Ciao, posso risolvere questa issue?

Ciao! Sì, hai proposte?

**Comment by Trafitto** [comment]
Si, se ho capito bene la issue volete suddividere tutti i comandi  in categoria ed avere un json tipo 
```
 frasi['buttons']
 {
    'button': 'bottone',
    'button2': 'bottone 2',
 }
```
Per le categorie guardando un po il file mi sono fatto questa idea 

- notice
- buttons
- commands
- locations
- actions

Con "locations" intendo i comandi tipo `home` e `forum`  e  "actions" be... le azioni tipo il download del csv o visualizza tweet

Rimarebbero fuori i messaggi "start" che potrebbero essere anche messi in una categoria omonima

**Comment by dag7dev** [comment]
Mi sembra un'ottima idea! Puoi iniziare a fare una bozza e vediamo come va!

**Comment by Trafitto** [comment]
Ciao, ho aggiunto le categorie e aggiornato il file, siccome non so come farlo partire ho cercato di cambiare il meno possibile :grin: 

Fammi sapere se c'e' qualcosa da cambiare #21

**Comment by dag7dev** [comment]
Closed by #21
