### ISSUE TITLE
Handler gruppi + regolamento non funzionanti

### ISSUE THREAD

**Issue by dag7dev** [dag7dev/MozItaReBot#23]
Come segnalato da @Trafitto bisogna investigare perché premendo i pulsanti "gruppi" e "regolamento" dopo aver premuto /start non succede nulla. Bisogna investigare....

**Comment by Trafitto** [comment]
Volendo posso dare un occhiata io

**Comment by Trafitto** [comment]
La pr #24

**Comment by dag7dev** [comment]
Closed by #24
