### ISSUE TITLE
 /vademecum: messaggio esplicativo vademecum + tre_bottoni per scaricare vademecum generale tecnico e common voice

### ISSUE THREAD

**Issue by dag7dev** [dag7dev/MozItaReBot#27]
Manda un testo con tre bottoni, ognuno dei quali deve poter inviare un file all'utente con l'ultima versione del vademecum disponibile.

Deve essere presa l'ultima versione da github.com/mozillaitalia/firefox-vademecum

**Comment by Mte90** [comment]
Non possiamo fare che mandi il link alla versione pdf e png? tanto le versioni sono compilate e presenti nel repo stesso.

**Comment by dag7dev** [comment]
> Non possiamo fare che mandi il link alla versione pdf e png? tanto le versioni sono compilate e presenti nel repo stesso.

Meglio di no. A parte che non so quanto verrebbe notata come funzionalità, ma l'utente sta più comodo se ha già un file bello pronto piuttosto che cliccare sul link.

**Comment by lorenzocamilli** [comment]
Ho fatto il comando in quetsione, per ora rimanda ai link pdf dei vari vademecum (attualmentec'è il link diretto alla versioni pdf del repo mozita, in base a come decidiamo valuto se metetre i link nel file "liste"). Non sono riuscito a far scaricare il file pdf e ritornarno come output all'utente, se qualcuno vuole provare possiamo lavorarci insieme, altrimenti sistemo questa versione e faccio una PR.
Ho trovato la pagina della [documentazione](https://docs.python-telegram-bot.org/en/stable/telegram.document.html) che potrebbe servirci, ma la devo ancora studiare bene.

**Comment by dag7dev** [comment]
Tu intendi "ho creato tre bottoni che rimandano all'ultima versione in questione di ogni vademecum"?

Anche se avevamo detto di mettere direttamente il file, credo che questa fosse l'idea originale di Daniele.

Se così fosse, per me possiamo mergearla così e aprire un altro issue come enhancement non prioritario ma non so... @Mte90 che ne pensi?

**Comment by lorenzocamilli** [comment]
> Tu intendi "ho creato tre bottoni che rimandano all'ultima versione di ogni vademecum"?

Si esatto, ora ogni bottone porta al rispettivo file pdf sul repo.
