### ISSUE TITLE
/regolamento: stringa + bottone che linka a "https://github.com/MozillaItalia/mozitaantispam_bot/wiki/Regolamento"

### ISSUE THREAD

**Issue by dag7dev** [dag7dev/MozItaReBot#9]
Task:
- [x]  Scrivere una pagina html in https://github.com/MozillaItalia/mozillaitalia.github.io con il regolamento attuale. L'url deve essere /regolamento.html . Quello che già c'è va bene
    - [x] OPZIONALE: aggiungere un link al regolamento nella homepage
- [ ] Scrivere il comando del bot che fetcha il regolamento da https://raw.githubusercontent.com/wiki/MozillaItalia/assets/Regolamento.md e lo sputa fuori su Telegram

**Comment by dag7dev** [comment]
@lorenzocamilli suggeriva che è un passo aggiuntivo e scomodo per l'utente finale (e ha ragione).

Opzioni possibili:
1. scrivere un pinnato in home su Telegram. Nel bot, fare il fetch di quel messaggio e mostrarlo.
2. scrivere il regolamento su un file markdown. Il bot si occuperà quindi di fare un fetch a quel file e di mostrarlo direttamente nella chat.
3. togliere questo comando poiché risulta ridondante (c'è già un regolamento nel gruppo home di telegram)

Ritengo che la migliore di tutte sia la numero 3:
- un utente non avvia un bot e legge le regole (se e quando le legge, lo fa appena è entrato in un gruppo)
- richiede tempo per implementarla a seconda del comportamento scelto
- ogni gruppo è gestito da MozIta, e hanno tutti lo stesso regolamento del gruppo Home (che poi sono le norme della buona comunicazione su Internet). A maggior ragione non ha senso avere un comando apposito.

È innegabile che bisogna provare a stilare un regolamento alternativo, un po' più adatto ad un messaggio e sintetico, siccome quello che c'è attualmente è parecchio prolisso e contiene informazioni che difficilmente un utente guarda.

**Comment by Mte90** [comment]
Il regolamento deve essere anche nel bot non solo dentro home perchè è utilizzato su più canali. Oltre al fatto che il bot è una vetrina, quando la gente entra passa prima nel bot e poi sceglie i canali.
Senza parlare che i messaggi pinnati li usano in pochi e certamente uno non ci penserebbe per cercare un regolamento.

Che sia un file markdown per me va benissimo, come anche fare una versione più corta.

**Comment by Trafitto** [comment]
Se posso dare la mia opinione nessuno legge il regolamento appena entrato in un gruppo, normalmente lo fa se gli viene segnalato qualcosa detto questo penso che il comando /regolamento debba inviare un messaggio con un link a qualcosa di esterno che una persona puo leggersi in tranquillita' se vuole.

Cosi anche quando un admin vuole segnalare qualcosa ad un utente puo' linkargli il regolamento

**Comment by Mte90** [comment]
Per me che sia un link va benissimo ma il comando deve rimanere, possiamo fare una pagina su https://github.com/MozillaItalia/mozillaitalia.github.io e risolviamo.

**Comment by dag7dev** [comment]
> nessuno legge il regolamento appena entrato in un gruppo, normalmente lo fa se gli viene segnalato qualcosa

Quoto in pieno.

> Per me che sia un link va benissimo ma il comando deve rimanere, possiamo fare una pagina su https://github.com/MozillaItalia/mozillaitalia.github.io e risolviamo.

Mi sembra un buon piano.

Ho aggiornato la issue.

**Comment by lorenzocamilli** [comment]
Ok ci sta, maagri lo facciamo come ultima cosa

**Comment by lorenzocamilli** [comment]
Attualmente il comando scarica il file del regolamento dal repo di mozita e lo mostra come messaggio. Non viene però mostrata la formattazione dei titoli (credo che proprio telegram non accetti i titoli) ma si vede "# Titolo" mentre il link viene formattatao corettamente.
Come vogliamo risolvere?

**Comment by Mte90** [comment]
potremmo farli in grassetto su telegram, mi pare che si faccia con **

**Comment by dag7dev** [comment]
non riusciamo a prendere il testo dal link del regolamento e sputarlo direttamente su Telegram come markdown formattato anziché scaricare il file?

-------- Original Message --------

**Comment by lorenzocamilli** [comment]
> potremmo farli in grassetto su telegram, mi pare che si faccia con **

Si bisognerebbe scaricarli in locale dal link e cambiare il file loclamente

**Comment by dag7dev** [comment]
> Ci posso provare ma credo rimanga il problema dei #

Vedi che riesci a fare, eventualmente si tolgono dalla pagina
